#!/usr/bin/env php
<?php

require "framework/vendor/autoload.php";

use \Shivergard\DreamApply\InitArtisan;

$artisan = new InitArtisan();

$app = $artisan->init("Mini Artisan for DreamApply  ", "mi mi mi");

$app->run();

