# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: phpunit/phpunit:5.0.3

pipelines:
    default:
      - step:
          script:
            - echo "Pipeline Init"
            - apt-get update
            - apt-get -qq install git-ftp
            - echo "'_$(git status -uno --porcelain | wc -l)_'"
            - git status -uno --porcelain
            - echo "Initiating Push site:Source."
            - git ftp init --user $FTP_USER --passwd $FTP_PASSWORD $FTP_SERVER